#+STARTUP: overview inlineimages

* General information
** Output file
See [[file:info.org][info.org]] for details.
** Authors
- Rafael Keller Tesser <rafael.tesser@inf.ufrgs.br>, PPGC/UFRGS
** Application
This a trace from =Ondes3D=, a model of the propagation of seismic waves. 
** Machine description 
The experiment was conducted on the [[https://www.grid5000.fr/mediawiki/index.php/Nancy:Hardware#Griffon][griffon]] cluster from the Nancy site of 
[[http://www.grid5000.fr][Grid'5000]]. We used 16 nodes, but only one process per node.

We ran experiments with MPI (OpenMPI) and Adaptive MPI (AMPI), which is an MPI implementation based on [[http://charm.cs.uiuc.edu][Charm++]]. The traces where generated by [[https://www.cs.uoregon.edu/research/tau/home.php][Tau]]. For the AMPI version, we also generated traces with a modified version of [[https://github.com/gmarkomanolis/mini][Mini]]. The mini traces where used to replay the execution using a modified version of [[http://simgrid.gforge.inria.fr/][SimGrid]], which generates traces in the [[http://sourceforge.net/projects/paje/][Paje]] format.

** Purpose of the experiment
We are working on extending SimGrid to simulate load balancing based on overdecomposition, in a similar fashion as AMPI. These traces should be used to compare the simulation in our modified SimGrid with an actual execution over AMPI. The purpose of this experiment is to analyse the accuracy of the simulation.

* Traces (stored in Dropbox):

[[https://www.dropbox.com/s/tlgbdjoj24v7u6q/MPI_16nodes.Tau.tbz?dl=0][MPI on 16 nodes (Tau traces)]]

[[https://www.dropbox.com/s/emrkrn5cxc7mztq/AMPI_16nodes.tbz?dl=0][AMPI on 16 nodes (Tau traces)]]

[[https://www.dropbox.com/s/dt6cv3tkq9wzkae/MPI_16nodes.Mini.tbz?dl=0][MPI on 16 nodes (Mini traces)]]

[[https://www.dropbox.com/s/2d63qv9cn7rwv4k/SMPI_REPLAY_16nodes.tbz?dl=0][Traces generated by SMPI replay (SimGrid)]]

* Discussions

**Merging Tau traces
The tau traces can be merged by entering their directory and executing following the command:

=tau_treemerge.pl=

This will generate two files: "tau.trc" and "tau.edf".

These traces can be converted to the Paje format using [[https://github.com/schnorr/akypuera][Akypuera]]. The conversion command would be:

=tau2paje --no-links tau.trc tau.edf > trace.paje=

One may also generate a Paje dump file, which can be read by [[https://github.com/soctrace-inria/framesoc][Framesoc]]. For this, you will need to install [[https://github.com/schnorr/pajeng][PajeNG]] and then execute:

=pj_dump --ignore-incomplete-links trace.paje > dump.paje=

